package com.cooker.fooddelivery.core

import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.data.jpa.repository.config.EnableJpaAuditing

@SpringBootConfiguration
@EnableAutoConfiguration
@EnableJpaAuditing
class FoodDeliveryTestConfiguration